# Generated by Django 4.0.3 on 2022-04-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feriadomodel_modificado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='feriadomodel',
            name='ano',
            field=models.IntegerField(default=2022),
        ),
    ]
